<?php
// Database Configuration Wizard
echo "=== User Management System Database Configuration Wizard ===\n\n";

// Check if db.php already exists and has valid configuration
$db_file = __DIR__ . '/config/db.php';
if (file_exists($db_file)) {
    echo "Found existing database configuration.\n";
    echo "Testing connection...\n";
    
    // Try to include and test the existing configuration
    ob_start();
    include $db_file;
    $error_output = ob_get_clean();
    
    if (empty($error_output) && isset($conn) && !$conn->connect_error) {
        echo "✓ Database connection successful!\n";
        echo "Your database is already configured correctly.\n";
        exit(0);
    } else {
        echo "✗ Database connection failed.\n";
        echo "We'll help you reconfigure it.\n\n";
    }
}

echo "Let's configure your database connection:\n\n";

// Get database configuration from user
echo "1. Database Host (usually 'localhost'): ";
$host = trim(fgets(STDIN)) ?: 'localhost';

echo "2. Database Name (should be 'user_management'): ";
$dbname = trim(fgets(STDIN)) ?: 'user_management';

echo "3. Database Username (often 'root'): ";
$username = trim(fgets(STDIN)) ?: 'root';

echo "4. Database Password (enter 'none' for no password): ";
$password = trim(fgets(STDIN));
if ($password === 'none') {
    $password = '';
}

echo "\nTesting connection with provided settings...\n";

// Test the connection
$connection_success = false;
$conn = null;

try {
    $conn = new mysqli($host, $username, $password, $dbname);
    if ($conn->connect_error) {
        echo "✗ Connection failed: " . $conn->connect_error . "\n";
    } else {
        echo "✓ Database connection successful!\n";
        $connection_success = true;
    }
} catch (Exception $e) {
    echo "✗ Connection failed: " . $e->getMessage() . "\n";
}

if ($connection_success) {
    // Create the new configuration file
    $config_content = "<?php
// Database configuration - Generated by Configuration Wizard
define('DB_HOST', '{$host}');
define('DB_USER', '{$username}');
define('DB_PASS', '{$password}');
define('DB_NAME', '{$dbname}');

// Create connection
\$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check connection
if (\$conn->connect_error) {
    die(\"Connection failed: \" . \$conn->connect_error);
}

// Set charset to UTF-8
\$conn->set_charset(\"utf8\");
?>
";
    
    // Write the configuration file
    if (file_put_contents($db_file, $config_content)) {
        echo "✓ Database configuration saved successfully!\n";
        echo "You can now run the application.\n";
    } else {
        echo "✗ Failed to save configuration file.\n";
        echo "Please make sure the config directory is writable.\n";
    }
} else {
    echo "\nUnable to establish database connection with provided settings.\n";
    echo "Please check:\n";
    echo "1. MySQL server is running\n";
    echo "2. Database '{$dbname}' exists\n";
    echo "3. User '{$username}' has access to the database\n";
    echo "4. Username and password are correct\n";
    echo "\nRefer to DATABASE_SETUP.md for detailed instructions.\n";
}

$conn->close();
?>