#!/usr/bin/env php
<?php
echo "=== User Management System Database Setup ===\n\n";

// This script helps set up the database for the User Management System
echo "This script will help you set up the database for the User Management System.\n";
echo "You'll need to provide your MySQL root credentials.\n\n";

// Get MySQL root credentials
echo "Enter MySQL root username (default: root): ";
$root_user = trim(fgets(STDIN)) ?: 'root';

echo "Enter MySQL root password (press Enter for no password): ";
$root_pass = trim(fgets(STDIN));

echo "Enter MySQL host (default: localhost): ";
$host = trim(fgets(STDIN)) ?: 'localhost';

echo "Enter MySQL port (default: 3306): ";
$port = trim(fgets(STDIN)) ?: '3306';

// Test connection with root credentials
echo "\nTesting connection with provided root credentials...\n";
$root_conn = null;

try {
    $root_conn = new mysqli($host, $root_user, $root_pass, '', $port);
    if ($root_conn->connect_error) {
        echo "✗ Connection failed: " . $root_conn->connect_error . "\n";
        exit(1);
    } else {
        echo "✓ Successfully connected to MySQL as root user.\n";
    }
} catch (Exception $e) {
    echo "✗ Connection failed: " . $e->getMessage() . "\n";
    exit(1);
}

// Create database
echo "\nCreating database 'user_management'...\n";
if ($root_conn->query("CREATE DATABASE IF NOT EXISTS user_management")) {
    echo "✓ Database 'user_management' created or already exists.\n";
} else {
    echo "✗ Failed to create database: " . $root_conn->error . "\n";
    $root_conn->close();
    exit(1);
}

// Create application user
echo "\nCreating application user 'user_mgmt'...\n";
$user_password = 'UserMgmt2025!'; // Default password for the application user

$create_user_sql = "CREATE USER IF NOT EXISTS 'user_mgmt'@'localhost' IDENTIFIED BY '$user_password'";
if ($root_conn->query($create_user_sql)) {
    echo "✓ User 'user_mgmt' created or already exists.\n";
} else {
    echo "✗ Failed to create user: " . $root_conn->error . "\n";
    $root_conn->close();
    exit(1);
}

// Grant privileges
echo "\nGranting privileges to 'user_mgmt'...\n";
$grant_sql = "GRANT ALL PRIVILEGES ON user_management.* TO 'user_mgmt'@'localhost'";
if ($root_conn->query($grant_sql)) {
    echo "✓ Privileges granted to 'user_mgmt'.\n";
} else {
    echo "✗ Failed to grant privileges: " . $root_conn->error . "\n";
    $root_conn->close();
    exit(1);
}

// Flush privileges
if ($root_conn->query("FLUSH PRIVILEGES")) {
    echo "✓ Privileges flushed.\n";
} else {
    echo "✗ Failed to flush privileges: " . $root_conn->error . "\n";
}

$root_conn->close();

// Connect with new user and import schema
echo "\nConnecting with new user 'user_mgmt'...\n";
$app_conn = null;

try {
    $app_conn = new mysqli($host, 'user_mgmt', $user_password, 'user_management', $port);
    if ($app_conn->connect_error) {
        echo "✗ Connection failed: " . $app_conn->connect_error . "\n";
        exit(1);
    } else {
        echo "✓ Successfully connected to MySQL as 'user_mgmt'.\n";
    }
} catch (Exception $e) {
    echo "✗ Connection failed: " . $e->getMessage() . "\n";
    exit(1);
}

// Import database schema
echo "\nImporting database schema...\n";
$schema_file = __DIR__ . '/database_schema.sql';

if (!file_exists($schema_file)) {
    echo "✗ Schema file not found: $schema_file\n";
    $app_conn->close();
    exit(1);
}

$schema_sql = file_get_contents($schema_file);
if ($app_conn->multi_query($schema_sql)) {
    // Wait for all queries to complete
    do {
        if ($result = $app_conn->store_result()) {
            $result->free();
        }
    } while ($app_conn->more_results() && $app_conn->next_result());
    
    echo "✓ Database schema imported successfully.\n";
} else {
    echo "✗ Failed to import schema: " . $app_conn->error . "\n";
    $app_conn->close();
    exit(1);
}

$app_conn->close();

// Create config file
echo "\nCreating database configuration file...\n";
$config_content = "<?php
// Database configuration - Generated by setup_database.php
define('DB_HOST', '$host');
define('DB_USER', 'user_mgmt');
define('DB_PASS', '$user_password');
define('DB_NAME', 'user_management');

// Create connection
\$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check connection
if (\$conn->connect_error) {
    die(\"Connection failed: \" . \$conn->connect_error);
}

// Set charset to UTF-8
\$conn->set_charset(\"utf8\");
?>
";

$config_file = __DIR__ . '/config/db.php';
if (file_put_contents($config_file, $config_content)) {
    echo "✓ Database configuration file created successfully.\n";
} else {
    echo "✗ Failed to create configuration file.\n";
    exit(1);
}

echo "\n=== Setup Complete ===\n";
echo "Database: user_management\n";
echo "Username: user_mgmt\n";
echo "Password: $user_password\n";
echo "Host: $host\n";
echo "Port: $port\n\n";
echo "You can now run the application!\n";
echo "To test the connection, run: php test_db.php\n";
?>